### ISSUE TITLE
Difference to Delta Chat

### ISSUE THREAD

**Issue by Hocuri** [open-xchange/ox-talk#39]
Hi, what is the difference to Delta Chat https://github.com/deltachat/deltachat-android/? DC seems to be further "developed" (already is on the Play Store and F-Droid) but has not such a nice icon :wink: 

Obviously, for the final product it might be the best to merge DC and ox-talk but this doesn't work very often :disappointed:

**Comment by Boehrsi** [comment]
Hi @Hocuri and thanks for the question. Currently the development state of the Delta Chat Android app is far ahead of the OX Talk app, that's true and for now we plan to implement most of the features the Delta Chat Core (https://github.com/deltachat/deltachat-core) provides. So OX Talk will get more similar to the Delta Chat Android app. 
But the apps will probably soon (or are already doing so) diverge a bit as OX Talk aims to implement all features and requirements of the [COI Spec](https://github.com/coi-dev/coi-specs/blob/master/coi-client-spec.md). In general both apps will hopefully be compatible to chat with each other while delivering different feature sets for different target groups. A bit like different IRC clients, they can be used to talk to each other, while different features or UIs are provided. 
Things like merging both projects highly depend on the level of difference between the both "final" products.

**Comment by Hocuri** [comment]
Thanks for your answer! :wink: 

> Currently the development state of the Delta Chat Android app is far ahead of the OX Talk app

So why not start over from the existing Delta Chat code? They didn't start from scratch, either, they used the Signal UI.

> Things like merging both projects highly depend on the level of difference between the both "final" products.

Actually I meant merging them now (i.e. as soon as possible). This would generate a lot of more discussions though. But then, we would have ONE client with all the nice features in the end :+1: 

For the record (although you probably already know it): [These are the DC specs](https://github.com/deltachat/spec/blob/master/spec.md#email-chat-specification) - [and other used standards](https://github.com/deltachat/deltachat-android/blob/master/standards.md#standards-used-in-delta-chat)

**Comment by Boehrsi** [comment]
> So why not start over from the existing Delta Chat code? They didn't start from scratch, either, they used the Signal UI.

The main reason is that we aren't using Java / Kotlin (or Swift for iOS) code to develop this app. We are using [Flutter](https://flutter.dev/) a Cross Platform solution. So sadly there is so to say nothing we could carry over from / to OX Talk. Beside that we probably wouldn't had used another UI as base, as we have some different requirements in regards to flexibility and adaptability, which would lead to rewrites of nearly everything we could base of. So we probably also had started from scratch even if we had used Java or Kotlin.

> Actually I meant merging them now (i.e. as soon as possible). This would generate a lot of more discussions though. But then, we would have ONE client with all the nice features in the end

Makes completely sense to focus efforts that's true. But due to slightly different targets and the completely different technical approach this is probably not feasible for neither of the both teams. But we are discussing stuff together and working together (e.g. I'm also working on the Delta Chat Android client and trying to bring up ideas for the Delta Chat Core, so in regards to your last sentence, yep I know the DC specs ;))

In general I think two different clients will emerge, both pushing each other, both for different target groups and both with (slightly?) different feature sets, but also both in the same ecosystem.

**Comment by webratte** [comment]
That's what we need. Many different Clients with different features and different UI. And all compatible.  :+1:

**Comment by Boehrsi** [comment]
I will close this issue for now, if new questions arise feel free to post again within this issue or just create a new one.
