### ISSUE TITLE
Another question ;-) Do you also plan a WP and iOS Version?

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-talk#47]
See the title ;-)

**Comment by Boehrsi** [comment]
An iOS version is already planned and due to the cross platform abilities of Flutter "only" the native layer between iOS and the Delta Chat Core needs to be developed / integrated to get a running iOS version. There is currently no ETA, as we plan to generally put the native C code and the Flutter / Dart code event closer together, to get rid of more and more platform specific stuff. But this also depends on the development progress on the Flutter framework. So sadly no ETA, but iOS will come. I think WP is currently not planned, sorry.

**Comment by webratte** [comment]
Thank you for your answer.

I'm sure COI will be a big thing in the near future :-)

**Comment by Boehrsi** [comment]
Thank you for your questions and interest and hopefully COI will shake up the chat world a bit. :+1:
